[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"