[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Set environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  framework = "#custom"
  publish = "dist"
  autoLaunch = true