[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install && INLINE_RUNTIME_CHUNK=false npm run build"
  publish = "dist"

[build.environment]
  # Force CSS processing to happen
  VITE_FORCE_POSTCSS = "true"
  NODE_ENV = "production"
  # Ensure PostCSS processes all files
  TAILWIND_MODE = "build"